[package]
name = "security_kernel"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
x86_64.workspace = true
spin.workspace = true
bitflags.workspace = true
volatile.workspace = true
common = { path = "../common" }

[[bin]]
name = "security_kernel"
path = "src/main.rs"
harness = false
