[package]
name = "host_kernel"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
x86_64.workspace = true
spin.workspace = true
bitflags.workspace = true
volatile.workspace = true
limine = "0.6"
x86 = "0.52.0"

[[bin]]
name = "host_kernel"
path = "src/main.rs"
harness = false



