[unstable]
build-std = ["core", "alloc"]

[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
runner = "qemu-system-x86_64 -kernel"
rustflags = [
    "-C", "link-arg=-Tlinker_x86_64.ld",
    "-C", "no-redzone", # Mandatory for x86_64 bare-metal kernels
]
